version: '3.8'

services:
  # varnish:
  #   build:
  #     context: ./docker/docker-config/varnish/
  #   depends_on:
  #     - nginx
  #   restart: always
  #   links:
  #     - nginx
  nginx:
    image: ghcr.io/marta-barea/martabarea-blog/nginx:latest
    ports:
      - 443:443
      - 80:80
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
    expose:
      - 443
      - 80
    restart: always
