version: '3.8'

services:
  # varnish:
  #   build:
  #     context: ./docker/docker-config/varnish/
  #   depends_on:
  #     - nginx
  #   restart: always
  #   links:
  #     - nginx
  nginx:
    image: ghcr.io/marta-barea/martabarea-blog/nginx:latest
    ports:
      - 8080:80
    expose:
      - 8080
    restart: always
