version: '3.8'

services:
  # varnish:
  #   build:
  #     context: ./docker/docker-config/varnish/
  #   depends_on:
  #     - nginx
  #   restart: always
  #   links:
  #     - nginx
  nginx:
    build:
      context: .
      dockerfile: ./docker/docker-config/nginx/Dockerfile
    ports:
      - 8080:80
    expose:
      - 8080
    restart: always
