version: '3.8'

services:
  varnish:
    image: ghcr.io/marta-barea/martabarea-blog/varnish:latest
    ports:
      - "443:443"
    depends_on:
      - nginx
    restart: always
  nginx:
    image: ghcr.io/marta-barea/martabarea-blog/nginx:latest
    ports:
      - "80:80"
      - "443:443"
    restart: always
