version: '3.8'

services:
  varnish:
    build:
      context: .
      dockerfile: ./docker/docker-config/varnish/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - nginx
    restart: always
  nginx:
    build:
      context: .
      dockerfile: ./docker/docker-config/nginx/Dockerfile
    volumes:
      - ./martabarea-blog/public:/var/www/martabarea-blog
      - ./docker/docker-config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
      - "443:443"
    restart: always
