name: Build and push Docker images & Deploy to server

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Varnish image
        uses: docker/build-push-action@v2
        with:
          context: docker/docker-config/varnish/
          push: true
          tags: ghcr.io/username/varnish:latest

      - name: Build and push Nginx image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/docker-config/nginx/Dockerfile
          push: true
          tags: ghcr.io/username/nginx:latest

      - name: Install ssh-agent
        run: |
          which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
          eval $(ssh-agent -s)

      - name: Add ssh key to ssh-agent
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Connect to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            docker-compose -f ./docker/docker-compose.yml up -d
